# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eed9c62102a175171e40ae316b31a487902e7e9e1725210a580e47e4601a3dff1cbfa79bb3565242779ba7b2e8d526dc8acc3b16542e0cceedcfdd6ec340460

test:
  secret_key_base: ac5d9a7893e12c771820c86c1a983cb079afa6aaabd974a4e8cadfff4d45351f53d8fcb6624859c95046f1b59d036a54bfbef0ef17b9e93aaa1673fcabe12a94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
